import { Keypair, PublicKey, sendAndConfirmTransaction } from "@solana/web3.js";
import { exit } from "process";
import { createSwapTransaction } from "./client";
import { getConnection } from "./utils";

const exampleDeployment = "testnet";

// this keypair is created only for this example. It has plenty of mocked USDC and USDT for the demo swap
const exampleKeyPair = Keypair.fromSecretKey(
  Uint8Array.from([
    213, 125, 55, 246, 235, 165, 230, 97, 173, 235, 79, 26, 171, 231, 156, 144, 82, 29, 86, 100, 41,
    137, 100, 52, 12, 207, 55, 183, 70, 150, 163, 145, 119, 185, 161, 160, 111, 85, 138, 184, 202,
    112, 148, 93, 161, 250, 124, 70, 132, 205, 255, 150, 83, 16, 90, 16, 51, 25, 180, 6, 255, 193,
    199, 66,
  ]),
);

// these are mocked USDC and USDT mint
const exampleUSDCMint = new PublicKey("3itb8x9GX7bxQ6eFfQT3E7CstkjaESizBpHNWB5wxjYY");
const exampleUSDTMint = new PublicKey("Hi4jco598zF6g4VM3uYfDaTvZFoMtX6TaTZZ9QdiVLUq");

// mocked USDC and USDT token account of the wallet from the keypair
const exampleUSDCTokenAccount = new PublicKey("J9ZWtE2vrSvEqLYsW3yEzAGSMvw2tFiVBNteQ6e565zy");
const exampleUSDTTokenAccount = new PublicKey("G5JJmV4qAtEE2dDJABn4iZ2W4RhdNM3xCDHw5SP1pafK");

// the example transaction logic
// this function established 2 transaction, first sell USDC for USDT and second sell USDT for USDC
// because we have to wallet keypair in code base, we just sign the transaction generated by the API
// directly with the wallet keypair
// in actually application, we should use wallet sdk for the signature
const exampleTransactions = async () => {
  const exampleConnection = getConnection(exampleDeployment);

  // example transaction 1: sell USDC for USDT
  const { transaction: transactionUSDCforUSDT, userTransferAuthority: tmpAuthorityA } =
    await createSwapTransaction(
      exampleKeyPair.publicKey,
      exampleConnection,
      exampleUSDCMint,
      exampleUSDTMint,
      exampleUSDCTokenAccount,
      exampleUSDTTokenAccount,
      "12.3",
      "10",
      exampleDeployment,
    );

  try {
    // may use wallet sdk for signature in application
    const signature = await sendAndConfirmTransaction(exampleConnection, transactionUSDCforUSDT, [
      tmpAuthorityA,
      exampleKeyPair,
    ]);
    console.info("transaction USDC -> USDT succeeded with signature: " + signature);
  } catch (e) {
    console.error("transaction USDC -> USDT failed with error: " + e);
    exit(1);
  }

  // example transaction 2: sell USDT for USDC
  const { transaction: transactionUSDTforUSDC, userTransferAuthority: tmpAuthorityB } =
    await createSwapTransaction(
      exampleKeyPair.publicKey,
      exampleConnection,
      exampleUSDTMint,
      exampleUSDCMint,
      exampleUSDTTokenAccount,
      exampleUSDCTokenAccount,
      "15.3",
      "10",
      exampleDeployment,
    );

  try {
    // may use wallet sdk for signature in application
    const signature = await sendAndConfirmTransaction(exampleConnection, transactionUSDTforUSDC, [
      tmpAuthorityB,
      exampleKeyPair,
    ]);
    console.info("transaction USDT -> USDC succeeded with signature: " + signature);
  } catch (e) {
    console.error("transaction USDT -> USDC failed with error: " + e);
    exit(1);
  }
};

// run the example transaction logic
exampleTransactions();
